function [] = change_parameters(A_Norton, n_Norton, n_x, c1, c2, c3, kappa1, kappa2, kappa3, eta1, eta2, eta3, B, m, K_yield, D, sigma1, A_nuc, stress_creep, strain_max, number_cycles, n_step)
f1=fopen('parameters_set.txt','wt');
pstring=num2str(A_Norton,9);
fprintf(f1,'%s ',pstring);
pstring=num2str(n_Norton,9);
fprintf(f1,'%s ',pstring);
if(n_x~=0)
    pstring=num2str(n_x,9);
    fprintf(f1,'%s ',pstring);
end
pstring=num2str(c1,9);
fprintf(f1,'%s ',pstring);
pstring=num2str(c2,9);
fprintf(f1,'%s ',pstring);
pstring=num2str(c3,9);
fprintf(f1,'%s ',pstring);
pstring=num2str(kappa1,9);
fprintf(f1,'%s ',pstring);
pstring=num2str(kappa2,9);
fprintf(f1,'%s ',pstring);
pstring=num2str(kappa3,9);
fprintf(f1,'%s ',pstring);
pstring=num2str(eta1,9);
fprintf(f1,'%s ',pstring);
pstring=num2str(eta2,9);
fprintf(f1,'%s ',pstring);
pstring=num2str(eta3,9);
fprintf(f1,'%s ',pstring);
pstring=num2str(B,9);
fprintf(f1,'%s ',pstring);
pstring=num2str(m,9);
fprintf(f1,'%s ',pstring);
pstring=num2str(K_yield,9);
fprintf(f1,'%s ',pstring);
pstring=num2str(D,9);
fprintf(f1,'%s ',pstring);
pstring=num2str(sigma1,9);
fprintf(f1,'%s ',pstring);
pstring=num2str(A_nuc,9);
fprintf(f1,'%s ',pstring);
pstring=num2str(stress_creep,9);
fprintf(f1,'%s ',pstring);
pstring=num2str(strain_max,9);
fprintf(f1,'%s ',pstring);
pstring=num2str(number_cycles,9);
fprintf(f1,'%s ',pstring);
pstring=num2str(n_step,9);
fprintf(f1,'%s ',pstring);
fclose(f1);
